Traceback (most recent call last):
  File "/Users/tliu/Github/comsc341-cd/venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tliu/Github/comsc341-cd/venv/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tliu/Github/comsc341-cd/venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tliu/.pyenv/versions/3.11.10/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tliu/Github/comsc341-cd/venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/tliu/Github/comsc341-cd/venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tliu/Github/comsc341-cd/venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# TODO: select the non-california rows from the `cali_merged` dataframe using the 'california' column
non_cali_data = None

# Creates the synthetic control by computing the weighted average of the `cigsale` outcome variable
synthetic_control = non_cali_data.groupby('year').apply(
    lambda x: np.dot(x['weight'], x['cigsale'])
).reset_index(name='synthetic_cigsale')

synthetic_control.head()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 5[0m
[1;32m      2[0m non_cali_data [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m      4[0m [38;5;66;03m# Creates the synthetic control by computing the weighted average of the `cigsale` outcome variable[39;00m
[0;32m----> 5[0m synthetic_control [38;5;241m=[39m [43mnon_cali_data[49m[38;5;241;43m.[39;49m[43mgroupby[49m([38;5;124m'[39m[38;5;124myear[39m[38;5;124m'[39m)[38;5;241m.[39mapply(
[1;32m      6[0m     [38;5;28;01mlambda[39;00m x: np[38;5;241m.[39mdot(x[[38;5;124m'[39m[38;5;124mweight[39m[38;5;124m'[39m], x[[38;5;124m'[39m[38;5;124mcigsale[39m[38;5;124m'[39m])
[1;32m      7[0m )[38;5;241m.[39mreset_index(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124msynthetic_cigsale[39m[38;5;124m'[39m)
[1;32m      9[0m synthetic_control[38;5;241m.[39mhead()

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'groupby'

